name: sphinx_env
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.13
  - babel=2.13.1
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - docutils=0.20.1
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - jinja2=3.1.2
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.44.0
  - libzlib=1.2.13
  - markupsafe=2.1.3
  - openssl=3.1.4
  - packaging=23.2
  - pip=23.3.1
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.12.0
  - python_abi=3.12
  - pytz=2023.3.post1
  - requests=2.31.0
  - setuptools=68.2.2
  - snowballstemmer=2.2.0
  - sphinx=7.2.6
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - tk=8.6.13
  - tzdata=2023c
  - urllib3=2.1.0
  - wheel=0.41.3
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - zipp=3.17.0
  - pip:
      - attrs==23.1.0
      - cattrs==23.1.2
      - esbonio==0.16.2
      - lsprotocol==2023.0.0b1
      - markdown-it-py==3.0.0
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - myst-parser==2.0.0
      - platformdirs==4.0.0
      - pygls==1.1.2
      - pyspellchecker==0.7.2
      - pyyaml==6.0.1
      - typeguard==4.1.5
