name: "Publish to GitHub Pages"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Sphinx
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "source/"
      - name: Commit changes
        run: |
          git clone https://github.com/manila-fairness/manila-fairness.github.io.git --branch gh-pages --single-branch gh-pages
          cp -r source/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "giordano.daloisio@gmail.com"
          git config --local user.name "giordanoDaloisio"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
